apiVersion: batch/v1
kind: Job
metadata: 
  name: db-migration
  namespace: {{ .Values.postgres.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: {{ .Values.postgres.migration_image }}:{{ .Values.postgres.migration_image_tag }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres_db_secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres_db_secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres_db_secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: >-
                postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)
                @postgres-service.{{ .Values.postgres.namespace }}.svc.cluster.local:5432
                /$(POSTGRES_DB)?sslmode=disable
          args:
            - -path=/app/migrations
            - -database=$(DATABASE_URL)
