apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/silasfrancis/my-devops-application.git
  username: silasfrancis
  password:  #gh auth token