apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/silasfrancis/multi-cloud-cicd-platform.git
  username: silasfrancis
  password:  #github pat removed after installation