version: "3"

tasks:
  
# install ArgoCD

  1:install-argo-cd:
    desc: Install Argo CD
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  2:apply repo secret:
    desc: Apply secret to access private repo
    cmds: 
      - kubectl apply -f repo-secret.yaml -n argocd

  3:apply-dev-application:
    desc: Apply dev application to dev cluster
    cmds: 
      - kubectl apply -f dev/app-dev.yaml -n argocd
  
  4:apply-main-application:
    desc: Apply main application to main cluster
    cmds: 
      - kubectl apply -f main/app-dev.yaml -n argocd
