apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: {{ .Values.apps.namespace }}
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.apps.fastapi.secretKey }}"
  JWT_SECRET_KEY: "{{ .Values.apps.fastapi.jwtSecretKey }}"
  POSTGRES_HOST: "postgres-service.{{ .Values.postgres.namespace }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
