apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: fastapi-gateway
  namespace: {{ .Values.apps.namespace }}
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      