apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fastapi-httproute
  namespace: {{ .Values.apps.namespace }}
spec:
  parentRefs:
    - name: fastapi-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: fastapi-service
          port: 80