apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: react-recoil-httproute
  namespace: {{ .Values.apps.namespace }}
spec:
  hostnames:
  - "{{ include "react-host-name" . }}"
  
  parentRefs:
    - name: react-recoil-gateway   
  rules:
    - matches: 
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: react-recoil-service
          port: 80